# Generated by Django 2.2.3 on 2019-07-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWordData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key_word', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
