# Generated by Django 2.2.3 on 2019-07-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_auto_20190713_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapi.KeyWordData'),
        ),
    ]
