# Generated by Django 2.2.3 on 2019-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0003_auto_20190713_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='title',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='title',
            field=models.ManyToManyField(to='testapi.KeyWordData'),
        ),
    ]
