# Generated by Django 2.2.3 on 2019-07-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0004_auto_20190713_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyworddata',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ('id',)},
        ),
    ]
