# Generated by Django 2.2.3 on 2019-07-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0005_auto_20190713_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyworddata',
            options={'ordering': ('key_word',)},
        ),
    ]
