# Generated by Django 2.2.3 on 2019-07-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0006_auto_20190714_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='title',
        ),
        migrations.AddField(
            model_name='keyworddata',
            name='videos',
            field=models.ManyToManyField(to='testapi.YouTubeVideo'),
        ),
    ]
