# Generated by Django 2.2.3 on 2019-07-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0009_keyworddata_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ('url',)},
        ),
    ]
